env:
  es2020: true

ignorePatterns:
  - dist

extends:
  - plugin:@lichtblick/base
  - plugin:@lichtblick/jest

overrides:
  - files: ["*.ts", "*.tsx"]
    extends:
      - plugin:@lichtblick/typescript
    parserOptions:
      project: [./tsconfig.json, ./tsconfig.dts.json]
  - files: ["example/**"]
    parserOptions:
      project: ./example/tsconfig.json
      
rules:
  "@lichtblick/no-boolean-parameters": off
